server:
  port: 8763
spring:
  profiles:
   active: dev
  application:
    name: eurekaclient
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性
    map-underscore-to-camel-case: true
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: ["text/xml","application/xml","application/json"]
      min-request-size: 2048
    response:
      enabled: true
riubbon:
  ReadTimeout: 60000
  ConnectTimeout: 10000
logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
    cn.jay.repository: debug
    cn.piesat.mapper: debug