server:
  port: 8081
  servlet:
    context-path: /spring-boot-grpc/
  tomcat:
    uri-encoding: UTF-8
grpc:
  client:
    apg-grpc-server:
      address: static://10.130.29.55:52051
    book-grpc-server:
      address: static://10.130.29.55:50051
    hello-grpc-server:
      address: static://10.130.29.55:51051
    GLOBAL:
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
logging:
  level:
    root: INFO